#!/bin/sh

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ln -sf ${SCRIPT_DIR}/gitconfig.symlink ~/.gitconfig
ln -sf ${SCRIPT_DIR}/zshrc.symlink ~/.zshrc
ln -sf ${SCRIPT_DIR}/janus ~/.janus

# iTerm2 config
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "${SCRIPT_DIR}/iterm2"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# vscode
ln -sf ${SCRIPT_DIR}/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
ln -sf ${SCRIPT_DIR}/vscode/keybindings.json ~/Library/Application\ Support/Code/User/keybindings.json
