#!/bin/sh

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ln -sf ${SCRIPT_DIR}/gitconfig.symlink ~/.gitconfig
ln -sf ${SCRIPT_DIR}/zshrc.symlink ~/.zshrc
ln -sf ${SCRIPT_DIR}/janus ~/.janus

# iTerm2 config
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "${SCRIPT_DIR}/iterm2"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
